<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Common extensions and utilities for working with ObjectPool.</Description>
    <PackageProjectUrl>$(PackageProjectUrl)tree/develop/src/ObjectPool</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <MinVerTagPrefix>objectpool-v</MinVerTagPrefix>
    <TargetFrameworks>net9.0;net10.0;</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ESCd.Extensions.ObjectPool.Tests" />

    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="8.0.22" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net9.0' ">
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="9.0.15" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="10.0.7" />
  </ItemGroup>

</Project>
