<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Common extensions and utilities for working with HttpClient.</Description>
    <PackageProjectUrl>$(PackageProjectUrl)tree/develop/src/Http</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <MinVerTagPrefix>http-v</MinVerTagPrefix>
    <TargetFrameworks>net8.0;net9.0;net10.0;</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ESCd.Extensions.Http.Tests" />

    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="8.0.30" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net9.0' ">
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="9.0.19" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="10.0.11" />
  </ItemGroup>

</Project>
