<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Common extensions and utilities for working with MemoryCache/DistributedCache.</Description>
    <PackageProjectUrl>$(PackageProjectUrl)tree/develop/src/Caching</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <MinVerTagPrefix>caching-v</MinVerTagPrefix>
    <TargetFrameworks>net8.0;net9.0;</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ESCd.Extensions.Caching.Tests" />
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net9.0' ">
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.9" />
  </ItemGroup>

</Project>
